version: 0.2

phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm install
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm run build

artifacts:
  files:
    - CODEBUILD_SRC_DIR/build
  discard-paths: yes
